# Generated by Django 5.2.5 on 2025-08-23 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_bankaccount_detailer_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailer',
            name='is_deleted',
        ),
    ]
