# Generated by Django 5.2.5 on 2025-08-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_detailer_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='booking_reference',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
